# Generated by Django 4.1.4 on 2023-01-08 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funko", "0003_orderdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="funko.cart"
            ),
            preserve_default=False,
        ),
    ]
