# Generated by Django 4.1.4 on 2023-01-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko', '0009_alter_orderfunko_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
